# Generated by Django 4.1.1 on 2022-09-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barir_malik', models.CharField(max_length=64)),
                ('pita_sami_nam', models.CharField(max_length=64)),
                ('nid_number', models.CharField(max_length=20)),
                ('holding_number', models.CharField(max_length=32)),
                ('mobile_no', models.CharField(max_length=32)),
                ('ward_number', models.IntegerField()),
                ('gramer_nam', models.CharField(max_length=128)),
                ('para_moholla', models.CharField(max_length=128)),
                ('purush_songkha', models.IntegerField()),
                ('mohila_songkha', models.IntegerField()),
                ('voter_songkha', models.IntegerField()),
                ('bosot_bari_type', models.CharField(max_length=64)),
                ('vita_jomi_poriman', models.IntegerField()),
                ('abadi_jomi_poriman', models.IntegerField()),
                ('jomi_in_shotangso', models.IntegerField()),
                ('latrin', models.BooleanField(default=True)),
                ('nolkup', models.BooleanField(default=True)),
                ('main_ay_source', models.CharField(max_length=64)),
                ('varatia_songkha', models.IntegerField(blank=True, null=True)),
                ('varatia_ay', models.IntegerField(blank=True, null=True)),
                ('protibondhi', models.BooleanField(default=False)),
                ('vikkhuk', models.BooleanField(default=False)),
                ('economic_class', models.CharField(max_length=64)),
                ('barshik_mullayon', models.IntegerField()),
                ('barshik_kor', models.IntegerField()),
            ],
        ),
    ]
