# Generated by Django 4.1.1 on 2022-09-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maguraunion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='mot',
            field=models.CharField(default=7, max_length=10, verbose_name='মোট'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='abadi_jomi_poriman',
            field=models.CharField(max_length=10, verbose_name='আবাদি জমির পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='barir_malik',
            field=models.CharField(max_length=64, verbose_name='বাড়ির মালিক'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='barshik_kor',
            field=models.CharField(max_length=64, verbose_name='বার্ষিক করের পরিমান'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='barshik_mullayon',
            field=models.CharField(max_length=64, verbose_name='বার্ষিক মূল্যায়ন'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='bosot_bari_type',
            field=models.CharField(max_length=64, verbose_name='বসত বাড়ির ধরণ'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='economic_class',
            field=models.CharField(max_length=64, verbose_name='অর্থনৈতিক শ্রেনী'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='gramer_nam',
            field=models.CharField(max_length=128, verbose_name='গ্রামের নাম'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='holding_number',
            field=models.CharField(max_length=32, verbose_name='হোল্ডিং নাম্বার'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='jomi_in_shotangso',
            field=models.CharField(max_length=10, verbose_name='জমি (শতাংশ)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='latrin',
            field=models.BooleanField(default=True, verbose_name='ল্যাট্রিন'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='main_ay_source',
            field=models.CharField(max_length=64, verbose_name='প্রধান আয়ের উৎস'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='mobile_no',
            field=models.CharField(max_length=32, verbose_name='মোবাইল নাম্বার'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='mohila_songkha',
            field=models.CharField(max_length=10, verbose_name='মহিলা'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='nid_number',
            field=models.CharField(max_length=20, verbose_name='এনআইডি নাম্বার'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='nolkup',
            field=models.BooleanField(default=True, verbose_name='নলকূপ'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='para_moholla',
            field=models.CharField(max_length=128, verbose_name='পাড়া/মহল্লা'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='pita_sami_nam',
            field=models.CharField(max_length=64, verbose_name='পিতা/স্বামীর নাম'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='protibondhi',
            field=models.BooleanField(default=False, verbose_name='প্রতিবন্ধী'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='purush_songkha',
            field=models.CharField(max_length=10, verbose_name='পুরুষ'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='varatia_ay',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ভাড়াটিয়া গৃহের আয়'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='varatia_songkha',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ভাড়াটিয়া গৃহের সংখ্যা'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='vikkhuk',
            field=models.BooleanField(default=False, verbose_name='ভিক্ষুক'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='vita_jomi_poriman',
            field=models.CharField(max_length=10, verbose_name='ভিটার পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='voter_songkha',
            field=models.CharField(max_length=10, verbose_name='ভোটার সংখ্যা'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='ward_number',
            field=models.CharField(max_length=5, verbose_name='ওয়ার্ড নং'),
        ),
    ]
