# Generated by Django 4.1.1 on 2022-09-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maguraunion', '0002_assessment_mot_alter_assessment_abadi_jomi_poriman_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assessment',
            table='অ্যাসেসমেন্ট টেবিল',
        ),
    ]
