# Generated by Django 4.1.1 on 2022-09-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maguraunion', '0003_alter_assessment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assessment',
            table=None,
        ),
    ]
