# Generated by Django 4.1.1 on 2022-09-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maguraunion', '0004_alter_assessment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='bosot_bari_type',
            field=models.CharField(choices=[('পাকা', 'পাকা'), ('আধা পাকা', 'আধা পাকা'), ('কাঁচা', 'কাঁচা')], max_length=64, verbose_name='বসত বাড়ির ধরণ'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='economic_class',
            field=models.CharField(choices=[('ধনী', 'ধনী'), ('মধ্যবিত্ত', 'মধ্যবিত্ত'), ('দরিদ্র', 'দরিদ্র'), ('হতদরিদ্র', 'হতদরিদ্র')], max_length=64, verbose_name='অর্থনৈতিক শ্রেনী'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='main_ay_source',
            field=models.CharField(choices=[('কৃষি', 'কৃষি'), ('ব্যাবসা', 'ব্যাবসা'), ('চাকুরী', 'চাকুরী'), ('দিনমজুর', 'দিনমজুর')], max_length=64, verbose_name='প্রধান আয়ের উৎস'),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ortho_bochor', models.CharField(max_length=32, verbose_name='অর্থবছর')),
                ('porishodh_status', models.BooleanField(default=False, verbose_name='পরিশোধ হয়েছে?')),
                ('somoy', models.DateTimeField(blank=True, null=True, verbose_name='তারিখ')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maguraunion.assessment', verbose_name='বাড়ির মালিক')),
            ],
        ),
    ]
