# Generated by Django 4.1.1 on 2022-09-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maguraunion', '0005_alter_assessment_bosot_bari_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='barshik_kor',
            field=models.CharField(default='৩০০', max_length=64, verbose_name='পরিমান'),
            preserve_default=False,
        ),
    ]
